# Generated by Django 5.2.6 on 2025-09-15 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="姓名")),
                ("age", models.IntegerField(verbose_name="年龄")),
                ("gender", models.CharField(max_length=10, verbose_name="性别")),
                ("title", models.CharField(max_length=100, verbose_name="职称")),
                (
                    "department",
                    models.CharField(max_length=100, verbose_name="所属部门"),
                ),
                (
                    "email",
                    models.EmailField(max_length=100, unique=True, verbose_name="邮箱"),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="联系电话")),
                (
                    "avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="头像URL"
                    ),
                ),
                ("hire_date", models.DateField(verbose_name="入职日期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="角色名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="角色描述")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True, to="auth.permission", verbose_name="权限列表"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeacherRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配时间"),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.role",
                        verbose_name="角色",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="teacher.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "教师角色关联",
                "verbose_name_plural": "教师角色关联",
                "unique_together": {("teacher", "role")},
            },
        ),
    ]
