# Generated by Django 5.2.6 on 2025-09-21 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("student", "0003_student_class_name_student_college_student_phone_and_more"),
        ("teacher", "0002_teacher_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="课程名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="课程代码"
                    ),
                ),
                ("credits", models.FloatField(verbose_name="学分")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="课程描述"),
                ),
                ("total_hours", models.IntegerField(verbose_name="总课时")),
                ("semester", models.CharField(max_length=50, verbose_name="开设学期")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程管理",
            },
        ),
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enroll_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="选课日期"),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="成绩"),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="student.student",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name": "选课记录",
                "verbose_name_plural": "选课管理",
                "unique_together": {("student", "course")},
            },
        ),
        migrations.CreateModel(
            name="TeachingAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assign_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="分配日期"),
                ),
                ("teaching_hours", models.IntegerField(verbose_name="授课课时")),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_assignments",
                        to="teacher.teacher",
                        verbose_name="教师",
                    ),
                ),
            ],
            options={
                "verbose_name": "授课记录",
                "verbose_name_plural": "授课管理",
                "unique_together": {("teacher", "course")},
            },
        ),
    ]
