# Generated by Django 5.2.6 on 2025-09-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Classroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="教室名称")),
                ("location", models.CharField(max_length=200, verbose_name="教室位置")),
                ("capacity", models.IntegerField(verbose_name="教室容量")),
                (
                    "equipment",
                    models.TextField(blank=True, null=True, verbose_name="教室设备"),
                ),
            ],
            options={
                "verbose_name": "教室",
                "verbose_name_plural": "教室管理",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[("required", "必修课"), ("elective", "选修课")],
                default="required",
                max_length=10,
                verbose_name="课程类型",
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="max_students",
            field=models.IntegerField(default=100, verbose_name="最大选课人数"),
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_of_week", models.IntegerField(verbose_name="星期几")),
                ("start_section", models.IntegerField(verbose_name="开始节次")),
                ("end_section", models.IntegerField(verbose_name="结束节次")),
                (
                    "week_pattern",
                    models.CharField(
                        choices=[("all", "每周"), ("odd", "单周"), ("even", "双周")],
                        default="all",
                        max_length=10,
                        verbose_name="上课周模式",
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="course.classroom",
                        verbose_name="教室",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="course.course",
                        verbose_name="课程",
                    ),
                ),
                (
                    "teaching_assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="course.teachingassignment",
                        verbose_name="授课记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "排课记录",
                "verbose_name_plural": "排课管理",
                "unique_together": {
                    ("classroom", "day_of_week", "start_section", "week_pattern"),
                    (
                        "teaching_assignment",
                        "day_of_week",
                        "start_section",
                        "week_pattern",
                    ),
                },
            },
        ),
    ]
