# Generated by Django 5.2.6 on 2025-09-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_classroom_course_course_type_course_max_students_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="teaching_method",
            field=models.CharField(
                choices=[("online", "线上"), ("offline", "线下")],
                default="offline",
                max_length=10,
                verbose_name="授课方式",
            ),
        ),
    ]
