# Generated by Django 5.2.6 on 2025-09-26 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_add_total_hours_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="classroom",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="course.classroom",
                verbose_name="上课教室",
            ),
        ),
        migrations.AlterField(
            model_name="classroom",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="教室编号/名称"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="max_students",
            field=models.IntegerField(default=50, verbose_name="总人数上限"),
        ),
    ]
