# Generated by Django 5.2.6 on 2025-09-18 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "学生", "verbose_name_plural": "学生管理"},
        ),
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(verbose_name="学生年龄"),
        ),
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="学生邮箱"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="gender",
            field=models.CharField(max_length=100, verbose_name="学生性别"),
        ),
        migrations.AlterField(
            model_name="student",
            name="major",
            field=models.CharField(max_length=100, verbose_name="学生专业"),
        ),
        migrations.AlterField(
            model_name="student",
            name="name",
            field=models.CharField(max_length=100, verbose_name="学生姓名"),
        ),
    ]
