# Generated by Django 5.2.6 on 2025-09-20 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0002_alter_student_options_alter_student_age_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="class_name",
            field=models.CharField(
                default="未分班", max_length=100, verbose_name="班级"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="college",
            field=models.CharField(
                default="未分学院", max_length=100, verbose_name="学院"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="电话"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_id",
            field=models.CharField(
                default=123456, max_length=100, unique=True, verbose_name="学号"
            ),
            preserve_default=False,
        ),
    ]
